/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;

/**
 *
 * @author Matheus
 */
public class TCadastroClientes extends javax.swing.JFrame {

    /**
     * Creates new form TCadastroClientes
     */
    public TCadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jTextField1Pesquisarcadstro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTextField1NomeCliente = new javax.swing.JTextField();
        jTextField2CPF = new javax.swing.JTextField();
        jTextField1CONTATO = new javax.swing.JTextField();
        jTextField3ENDERECO = new javax.swing.JTextField();
        jTextField4CIDADE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FUNDO = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Contato", "Endereço"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 70, 620, 91);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Nome:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 20, 60, 22);
        jPanel1.add(jTextField1Pesquisarcadstro);
        jTextField1Pesquisarcadstro.setBounds(90, 20, 150, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("OU");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 20, 27, 22);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("CPF:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 20, 50, 22);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(360, 20, 130, 30);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/magnifier.png"))); // NOI18N
        jButton4.setText("PESQUISAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(500, 20, 110, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 230, 630, 220);

        jTextField1NomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1NomeClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1NomeCliente);
        jTextField1NomeCliente.setBounds(90, 30, 290, 30);

        jTextField2CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2CPFActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2CPF);
        jTextField2CPF.setBounds(80, 70, 150, 30);

        jTextField1CONTATO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1CONTATOActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1CONTATO);
        jTextField1CONTATO.setBounds(110, 110, 150, 30);

        jTextField3ENDERECO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ENDERECOActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3ENDERECO);
        jTextField3ENDERECO.setBounds(110, 150, 260, 30);

        jTextField4CIDADE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4CIDADEActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4CIDADE);
        jTextField4CIDADE.setBounds(100, 190, 140, 30);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 100, 80, 23);

        jButton2.setText("Salvar");
        getContentPane().add(jButton2);
        jButton2.setBounds(500, 60, 80, 23);

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(500, 20, 80, 23);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("CPF:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 80, 50, 20);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 110, 70);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Contato:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 100, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Cidade:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 200, 68, 22);

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/fundo-embacado-pessoas-embacadas-que-fazem-compras-no-fundo-do-supermercado_7190-2027.jpg"))); // NOI18N
        getContentPane().add(FUNDO);
        FUNDO.setBounds(0, -50, 640, 500);

        setSize(new java.awt.Dimension(638, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1NomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1NomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1NomeClienteActionPerformed

    private void jTextField1CONTATOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1CONTATOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1CONTATOActionPerformed

    private void jTextField4CIDADEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4CIDADEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4CIDADEActionPerformed

    private void jTextField3ENDERECOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ENDERECOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ENDERECOActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2CPFActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TCadastroClientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1CONTATO;
    private javax.swing.JTextField jTextField1NomeCliente;
    private javax.swing.JTextField jTextField1Pesquisarcadstro;
    private javax.swing.JTextField jTextField2CPF;
    private javax.swing.JTextField jTextField3ENDERECO;
    private javax.swing.JTextField jTextField4CIDADE;
    // End of variables declaration//GEN-END:variables

    void seVisible(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
