/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISAO;

import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class TELADELOGIN extends javax.swing.JFrame {

    /**
     * Creates new form TELADELOGIN
     */
    public TELADELOGIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BOTAOENTRAR = new javax.swing.JButton();
        jButton2sair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        lblSENHA = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        FUNDO = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/Chave 2.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setResizable(false);
        getContentPane().setLayout(null);

        BOTAOENTRAR.setText("Entrar");
        BOTAOENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTAOENTRARActionPerformed(evt);
            }
        });
        getContentPane().add(BOTAOENTRAR);
        BOTAOENTRAR.setBounds(240, 160, 73, 23);

        jButton2sair.setText("Sair");
        jButton2sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2sairActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2sair);
        jButton2sair.setBounds(330, 160, 51, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel3.setText("Sistem.POSTOS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 0, 330, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/Chave 2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 40, 260, 260);

        lblusuario.setText("Usuário:");
        getContentPane().add(lblusuario);
        lblusuario.setBounds(230, 80, 40, 20);

        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(usuario);
        usuario.setBounds(280, 80, 110, 20);

        lblSENHA.setText("Senha:");
        getContentPane().add(lblSENHA);
        lblSENHA.setBounds(230, 120, 34, 14);

        senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaKeyPressed(evt);
            }
        });
        getContentPane().add(senha);
        senha.setBounds(280, 120, 110, 20);

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEM/FUNDO.png"))); // NOI18N
        getContentPane().add(FUNDO);
        FUNDO.setBounds(0, 0, 540, 340);

        setSize(new java.awt.Dimension(550, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void BOTAOENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTAOENTRARActionPerformed
  
      if(usuario.getText().equals("Franzoni") && senha.getText().equals("1234")){
        TELAPRINCIPAL tela = new TELAPRINCIPAL();
        tela.setVisible(true);
        dispose();
        
    }                                              
        else{
            JOptionPane.showMessageDialog(rootPane, "Acesso Negado! Tente novamente");
        }
    }//GEN-LAST:event_BOTAOENTRARActionPerformed

    private void jButton2sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2sairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton2sairActionPerformed

    private void senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaKeyPressed
     
     
    }//GEN-LAST:event_senhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TELADELOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TELADELOGIN().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTAOENTRAR;
    private javax.swing.JLabel FUNDO;
    private javax.swing.JButton jButton2sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblSENHA;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
